### ISSUE TITLE
Error en SP GET_ALL_ARTICULOS

### ISSUE THREAD

**Issue by tinchoabbate** [tinchoabbate/restaurant#33]
En el listado de articulos no aparecen algunos articulos, imagino que son los que nunca fueron pedidos, y debe ser por ese inner join. Si no me equivoco debería ser left join, fijate.
![imagen](https://user-images.githubusercontent.com/8171248/30250126-c4c5d6be-961f-11e7-9c25-7339f55ef7f1.png)

**Comment by alejo1206** [comment]
probe el sp y anda bien. cambie el inner por left y cree un articulo nuevo y lo listo sin problemas
