### ISSUE TITLE
Error en getOneByTable de PedidoAdapter

### ISSUE THREAD

**Issue by tinchoabbate** [tinchoabbate/restaurant#46]
![imagen](https://user-images.githubusercontent.com/8171248/30296293-0d4dbd0c-971a-11e7-8e24-e5e742ec019c.png)

**Comment by alejo1206** [comment]
ya esta arreglado el error en el metodo pero cuando quiero ver el pedido de la mesa indicada, el sistema no hace nada (osea que no anda el href "ver pedido")

**Comment by tinchoabbate** [comment]
Ok, subi esos cambios que arreglan el error y lo reviso
